// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyoWdQ4hz4M0lxoSAofGnqg83nhRFU9lY',
    appId: '1:253794708598:web:5ea5499a0c1e8b31924357',
    messagingSenderId: '253794708598',
    projectId: 'ecommerceapp-92581',
    authDomain: 'ecommerceapp-92581.firebaseapp.com',
    storageBucket: 'ecommerceapp-92581.appspot.com',
    measurementId: 'G-31YKHRRHCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaTZmU9LZ4Q57vFznTibXCCYHejUb6aMA',
    appId: '1:253794708598:android:e4d2f5d7f7426bb8924357',
    messagingSenderId: '253794708598',
    projectId: 'ecommerceapp-92581',
    storageBucket: 'ecommerceapp-92581.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCovC_miMmZ7dJKiGNiSicFlmRbpjhETQI',
    appId: '1:253794708598:ios:04108c1c2938bb72924357',
    messagingSenderId: '253794708598',
    projectId: 'ecommerceapp-92581',
    storageBucket: 'ecommerceapp-92581.appspot.com',
    androidClientId: '253794708598-m28na8rm8f90u4r2o74u81u0aob4ucne.apps.googleusercontent.com',
    iosClientId: '253794708598-tc2h8nl7bcalklgpafmi41hitogvhvmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCovC_miMmZ7dJKiGNiSicFlmRbpjhETQI',
    appId: '1:253794708598:ios:04108c1c2938bb72924357',
    messagingSenderId: '253794708598',
    projectId: 'ecommerceapp-92581',
    storageBucket: 'ecommerceapp-92581.appspot.com',
    androidClientId: '253794708598-m28na8rm8f90u4r2o74u81u0aob4ucne.apps.googleusercontent.com',
    iosClientId: '253794708598-tc2h8nl7bcalklgpafmi41hitogvhvmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyoWdQ4hz4M0lxoSAofGnqg83nhRFU9lY',
    appId: '1:253794708598:web:4ad92241769bd9c6924357',
    messagingSenderId: '253794708598',
    projectId: 'ecommerceapp-92581',
    authDomain: 'ecommerceapp-92581.firebaseapp.com',
    storageBucket: 'ecommerceapp-92581.appspot.com',
    measurementId: 'G-TW2TNMJSZD',
  );

}