name: e_commerce_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

#----------------------Packages------------------------#
dependencies:
  flutter:
    sdk: flutter


  #Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.1.10

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  #State Management
  get_it: ^7.2.0
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  firebase_core: ^2.29.0
  lottie: ^3.1.0
  connectivity_plus: ^6.0.3
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  google_sign_in: ^6.2.1
  shimmer: ^3.0.0
  image_picker: ^1.1.1
  firebase_storage: ^11.7.5
  cached_network_image: ^3.3.1

  #Product Specific



  #-----------------------End Packages-------------------------#


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  #----------------------Local Assets-------------------------#
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/product_banner_images/
    - assets/images/products/shoes/
    - assets/images/products/jackets/
    - assets/images/profile/

  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 800
  #----------------------End Local Assets-------------------------#
